# Generated by Django 5.0.2 on 2024-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
