# Generated by Django 5.0.2 on 2024-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_alter_item_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pi',
            field=models.CharField(default='', max_length=255),
        ),
    ]
